spring-boot-plus:
  # 是否启用ansi控制台输出有颜色的字体，local环境建议开启，服务器环境设置为false
  enable-ansi: true
  # 请求日志在控制台是否格式化输出，local环境建议开启，服务器环境设置为false
  request-log-format: true
  # 响应日志在控制台是否格式化输出，local环境建议开启，服务器环境设置为false
  response-log-format: true
  # 登录设置
  login:
    token-valid-time: 60  # 登录token失效时间，单位分钟

  # 拦截器配置
  interceptor-config:
    resource-config:
      include-path: ${spring-boot-plus.resource-access-patterns}
  # 文件上传下载配置
  upload-path: /opt/upload/
  # 资源访问路径
  resource-access-path: /resource/
  # 资源访问路径匹配：/resource/**
  resource-access-patterns: ${spring-boot-plus.resource-access-path}**
  # 资源访问全路径前缀：http://localhost:8900/resource/
  resource-access-url: http://localhost:${server.port}${server.servlet.context-path}${spring-boot-plus.resource-access-path}
